require("core.config.colorscheme")
require("core.config.treesitter")
require("core.config.lualine")
require("core.config.telescope")
require("core.config.lsp")
require("core.config.diagnostic")
-- require("core.config.markdown_preview")
